package restc

const (
	// Application types.
	TypeApplicationAtomXML             = "application/atom+xml"
	TypeApplicationCBOR                = "application/cbor"
	TypeApplicationEDI                 = "application/EDI-X12"
	TypeApplicationEDIFACT             = "application/EDIFACT"
	TypeApplicationFormURLEncoded      = "application/x-www-form-urlencoded"
	TypeApplicationGeoJSON             = "application/geo+json"
	TypeApplicationGZIP                = "application/gzip"
	TypeApplicationHALJSON             = "application/hal+json"
	TypeApplicationJSON                = "application/json"
	TypeApplicationJSONPatch           = "application/json-patch+json"
	TypeApplicationJSONProblem         = "application/problem+json"
	TypeApplicationJavascript          = "application/javascript"
	TypeApplicationLDJSON              = "application/ld+json"
	TypeApplicationMSAccess            = "application/msaccess"
	TypeApplicationMSWord              = "application/msword"
	TypeApplicationMsgPack             = "application/msgpack"
	TypeApplicationNDJSON              = "application/x-ndjson"
	TypeApplicationOctetStream         = "application/octet-stream"
	TypeApplicationOGG                 = "application/ogg"
	TypeApplicationOpenXMLSheet        = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
	TypeApplicationOpenXMLPresentation = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
	TypeApplicationOpenXMLWord         = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
	TypeApplicationPDF                 = "application/pdf"
	TypeApplicationProtobuf            = "application/x-protobuf"
	TypeApplicationRAR                 = "application/vnd.rar"
	TypeApplicationRTF                 = "application/rtf"
	TypeApplicationSVGXML              = "application/svg+xml"
	TypeApplicationTAR                 = "application/x-tar"
	TypeApplicationTypescript          = "application/typescript"
	TypeApplicationWASM                = "application/wasm"
	TypeApplicationXHTML               = "application/xhtml+xml"
	TypeApplicationXML                 = "application/xml"
	TypeApplicationXMLDTD              = "application/xml-dtd"
	TypeApplicationXMLProblem          = "application/problem+xml"
	TypeApplicationYAML                = "application/x-yaml"
	TypeApplicationZIP                 = "application/zip"
	TypeApplication7ZIP                = "application/x-7z-compressed"

	// Multipart types.
	TypeMultipartAlternative = "multipart/alternative"
	TypeMultipartFormData    = "multipart/form-data"
	TypeMultipartMixed       = "multipart/mixed"
	TypeMultipartRelated     = "multipart/related"

	// Text types.
	TypeTextCalendar   = "text/calendar"
	TypeTextCSS        = "text/css"
	TypeTextCSV        = "text/csv"
	TypeTextHTML       = "text/html"
	TypeTextJavascript = "text/javascript"
	TypeTextMarkdown   = "text/markdown"
	TypeTextPLAIN      = "text/plain"
	TypeTextVCard      = "text/vcard"
	TypeTextXML        = "text/xml"
	TypeTextYAML       = "text/yaml"

	// Image types.
	TypeImageAPNG   = "image/apng"
	TypeImageAVIF   = "image/avif"
	TypeImageBMP    = "image/bmp"
	TypeImageGIF    = "image/gif"
	TypeImageICO    = "image/x-icon"
	TypeImageJPG    = "image/jpeg"
	TypeImagePNG    = "image/png"
	TypeImageSVGXML = "image/svg+xml"
	TypeImageTIFF   = "image/tiff"
	TypeImageWEBP   = "image/webp"

	// Video types.
	TypeVideoAVI       = "video/x-msvideo"
	TypeVideoFLV       = "video/x-flv"
	TypeVideoM3U8      = "application/x-mpegURL"
	TypeVideoMP4       = "video/mp4"
	TypeVideoMPEG      = "video/mpeg"
	TypeVideoOGG       = "video/ogg"
	TypeVideoQUICKTIME = "video/quicktime"
	TypeVideoTS        = "video/MP2T"
	TypeVideoWEBM      = "video/webm"
	TypeVideoWMV       = "video/x-ms-wmv"

	// Audio types.
	TypeAudioAAC  = "audio/aac"
	TypeAudioFLAC = "audio/flac"
	TypeAudioMIDI = "audio/midi"
	TypeAudioMP3  = "audio/mpeg"
	TypeAudioMP4  = "audio/mp4"
	TypeAudioOGG  = "audio/ogg"
	TypeAudioOPUS = "audio/opus"
	TypeAudioWAV  = "audio/x-wav"
	TypeAudioWEBM = "audio/webm"
	TypeAudioWMV  = "audio/x-ms-wma"

	// Font types.
	TypeFontOTF   = "font/otf"
	TypeFontTTF   = "font/ttf"
	TypeFontWOFF  = "font/woff"
	TypeFontWOFF2 = "font/woff2"
)
