package restc

const (
	TypeApplicationAtomXML        = "application/atom+xml"
	TypeApplicationFormURLEncoded = "application/x-www-form-urlencoded"
	TypeApplicationJSON           = "application/json"
	TypeApplicationOctetStream    = "application/octet-stream"
	TypeApplicationSVGXML         = "application/svg+xml"
	TypeApplicationXML            = "application/xml"
	TypeApplicationJavascript     = "application/javascript"
	TypeApplicationTypescript     = "application/typescript"
	TypeApplicationPDF            = "application/pdf"
	TypeApplicationRTF            = "application/rtf"
	TypeApplicationXHTML          = "application/xhtml+xml"
	TypeApplicationTAR            = "application/x-tar"
	TypeApplicationZIP            = "application/zip"
	TypeApplication7ZIP           = "application/x-7z-compressed"
	TypeApplicationMSWORD         = "application/msword"
	TypeMultipartFormData         = "multipart/form-data"
	TypeFontTTF                   = "font/ttf"
	TypeFontOTF                   = "font/otf"
	TypeTextHTML                  = "text/html"
	TypeTextPLAIN                 = "text/plain"
	TypeTextXML                   = "text/xml"
	TypeTextCSS                   = "text/css"
	TypeTextCSV                   = "text/csv"
	TypeImageBMP                  = "image/bmp"
	TypeImageGIF                  = "image/gif"
	TypeImageJPG                  = "image/jpeg"
	TypeImagePNG                  = "image/png"
	TypeImageTIFF                 = "image/tiff"
	TypeImageSVGXML               = "image/svg+xml"
	TypeImageWEBP                 = "image/webp"
	TypeVideoAVI                  = "video/x-msvideo"
	TypeVideoMPEG                 = "video/mpeg"
	TypeVideoWEBM                 = "video/webm"
	TypeAudioWAV                  = "audio/x-wav"
	TypeAudioWEBM                 = "audio/webm"
)
