package restc

const (
	// Standard request headers.
	Accept             = "Accept"
	AcceptCharset      = "Accept-Charset"
	AcceptEncoding     = "Accept-Encoding"
	AcceptLanguage     = "Accept-Language"
	AcceptDatetime     = "Accept-Datetime"
	Authorization      = "Authorization"
	CacheControl       = "Cache-Control"
	Connection         = "Connection"
	ContentLength      = "Content-Length"
	ContentMD5         = "Content-MD5"
	ContentType        = "Content-Type"
	Cookie             = "Cookie"
	Date               = "Date"
	DoNotTrack         = "DNT"
	Expect             = "Expect"
	Forwarded          = "Forwarded"
	From               = "From"
	Host               = "Host"
	IfMatch            = "If-Match"
	IfModifiedSince    = "If-Modified-Since"
	IfNoneMatch        = "If-None-Match"
	IfRange            = "If-Range"
	IfUnmodifiedSince  = "If-Unmodified-Since"
	MaxForwards        = "Max-Forwards"
	Origin             = "Origin"
	Pragma             = "Pragma"
	ProxyAuthorization = "Proxy-Authorization"
	Range              = "Range"
	Referer            = "Referer"
	TE                 = "TE"
	Trailer            = "Trailer"
	TransferEncoding   = "Transfer-Encoding"
	UserAgent          = "User-Agent"
	Via                = "Via"
	Warning            = "Warning"

	// Standard response headers.
	AcceptPatch             = "Accept-Patch"
	AcceptRanges            = "Accept-Ranges"
	Age                     = "Age"
	Allow                   = "Allow"
	AltSvc                  = "Alt-Svc"
	ContentDisposition      = "Content-Disposition"
	ContentEncoding         = "Content-Encoding"
	ContentLanguage         = "Content-Language"
	ContentLocation         = "Content-Location"
	ContentRange            = "Content-Range"
	ETag                    = "ETag"
	Expires                 = "Expires"
	LastModified            = "Last-Modified"
	Link                    = "Link"
	Location                = "Location"
	P3P                     = "P3P"
	ProxyAuthenticate       = "Proxy-Authenticate"
	Refresh                 = "Refresh"
	RetryAfter              = "Retry-After"
	Server                  = "Server"
	SetCookie               = "Set-Cookie"
	StrictTransportSecurity = "Strict-Transport-Security"
	Upgrade                 = "Upgrade"
	Vary                    = "Vary"
	WWWAuthenticate         = "WWW-Authenticate"

	// Security & CORS headers.
	AccessControlAllowCredentials   = "Access-Control-Allow-Credentials"
	AccessControlAllowHeaders       = "Access-Control-Allow-Headers"
	AccessControlAllowMethods       = "Access-Control-Allow-Methods"
	AccessControlAllowOrigin        = "Access-Control-Allow-Origin"
	AccessControlExposeHeaders      = "Access-Control-Expose-Headers"
	AccessControlMaxAge             = "Access-Control-Max-Age"
	AccessControlRequestHeaders     = "Access-Control-Request-Headers"
	AccessControlRequestMethod      = "Access-Control-Request-Method"
	ClearSiteData                   = "Clear-Site-Data"
	ContentSecurityPolicy           = "Content-Security-Policy"
	ContentSecurityPolicyReportOnly = "Content-Security-Policy-Report-Only"
	CrossOriginEmbedderPolicy       = "Cross-Origin-Embedder-Policy"
	CrossOriginOpenerPolicy         = "Cross-Origin-Opener-Policy"
	CrossOriginResourcePolicy       = "Cross-Origin-Resource-Policy"
	NEL                             = "NEL"
	PermissionsPolicy               = "Permissions-Policy"
	ReferrerPolicy                  = "Referrer-Policy"
	ReportTo                        = "Report-To"
	TimingAllowOrigin               = "Timing-Allow-Origin"

	// Client Hints & Fetch Metadata.
	SecCHUA                 = "Sec-CH-UA"
	SecCHUAMobile           = "Sec-CH-UA-Mobile"
	SecCHUAPlatform         = "Sec-CH-UA-Platform"
	SecFetchDest            = "Sec-Fetch-Dest"
	SecFetchMode            = "Sec-Fetch-Mode"
	SecFetchSite            = "Sec-Fetch-Site"
	SecFetchUser            = "Sec-Fetch-User"
	SecGPC                  = "Sec-GPC"
	SaveData                = "Save-Data"
	UpgradeInsecureRequests = "Upgrade-Insecure-Requests"

	// Non-Standard headers.
	XAspNetVersion                = "X-AspNet-Version"
	XAspNetMvcVersion             = "X-AspNetMvc-Version"
	XContentSecurityPolicy        = "X-Content-Security-Policy"
	XContentTypeOptions           = "X-Content-Type-Options"
	XCSRFToken                    = "X-CSRF-Token" //nolint:gosec
	XCorrelationId                = "X-Correlation-Id"
	XDNSPrefetchControl           = "X-DNS-Prefetch-Control"
	XDownloadOptions              = "X-Download-Options"
	XForwardedFor                 = "X-Forwarded-For"
	XForwardedProto               = "X-Forwarded-Proto"
	XFrameOptions                 = "X-Frame-Options"
	XHTTPMethodOverride           = "X-HTTP-Method-Override"
	XPermittedCrossDomainPolicies = "X-Permitted-Cross-Domain-Policies"
	XPoweredBy                    = "X-Powered-By"
	XRealIP                       = "X-Real-IP"
	XRequestedWith                = "X-Requested-With"
	XRequestId                    = "X-Request-Id"
	XRobotsTag                    = "X-Robots-Tag"
	XRatelimitLimit               = "X-Ratelimit-Limit"
	XRatelimitRemaining           = "X-Ratelimit-Remaining"
	XRatelimitReset               = "X-Ratelimit-Reset"
	XTraceId                      = "X-Trace-Id"
	XUACompatible                 = "X-UA-Compatible"
	XXSSProtection                = "X-XSS-Protection"
)
